name: Deploy Hugo site to Pages
on:
  push:
    branches: ["main"] # 只要你向 main 分支推送代码，就触发
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # 关键！这步会把你的主题文件也拉取过去
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true # 开启扩展版，支持 PaperMod 等主题需要的 Sass 加密
      - name: Build
        run: hugo --gc --minify # 运行 Hugo 编译命令，压缩文件
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public # 告诉 GitHub，编译出来的网页在 public 文件夹里
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
